import React, { useState } from 'react';
import { Atom, Sparkles, BarChart3, FlaskConical, GitCompareArrows, FileDown, Info, Search, AlertTriangle, ArrowRight } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, RadarChart, PolarGrid, PolarAngleAxis, Radar } from 'recharts';
import { DisclaimerAlert } from './SinglePredictor';

const Empty = ({ onNavigate, text = 'Run a prediction to populate this research view.' }) => <div className="empty-state"><Atom size={34}/><p>{text}</p><button className="btn-primary" onClick={() => onNavigate('single')}>Open prediction lab <ArrowRight size={16}/></button></div>;
const title = { molecule:['Molecule visualization', Atom], explain:['Explainable AI', Sparkles], analytics:['Toxicity analytics', BarChart3], descriptors:['Chemical descriptors', FlaskConical], similarity:['Similarity search', GitCompareArrows], report:['Report generator', FileDown], about:['About OcularTox AI', Info] };
function DescriptorPanel({ result }) { const p=result.properties||{}; const fields=[['Compound Name',result.compound_name],['Molecular Formula',p.formula],['Canonical SMILES',result.canonical_smiles],['Molecular Weight',p.mw],['Exact Mass',p.exact_mass],['LogP',p.logp],['Heavy Atoms',p.heavy_atoms],['Num Atoms',p.num_atoms],['Num Bonds',p.num_bonds]]; const radar=[{k:'Size',v:Math.min((p.mw||0)/500*100,100)},{k:'Lipophilicity',v:Math.min(Math.max((p.logp||0)/5*100,0),100)},{k:'Polarity',v:Math.min((p.tpsa||0)/140*100,100)},{k:'Flexibility',v:Math.min((p.rotb||0)/10*100,100)},{k:'3D character',v:(p.fraction_csp3||0)*100}]; return <><section className="property-grid descriptor-grid">{fields.map(([k,v])=><div className="prop-box" key={k}><span>{k}</span><strong className={k==='Canonical SMILES'?'small-value':''}>{v??'—'}</strong></div>)}</section><section className="descriptor-lower"><div className="glass-card"><h2>Lipinski Rule of Five</h2><p className="muted">A simple oral drug-likeness screen, not a toxicity verdict.</p><div className="ro5-list">{[['MW ≤ 500',p.lipinski_ro5?.mw_pass],['LogP ≤ 5',p.lipinski_ro5?.logp_pass],['H-bond donors ≤ 5',p.lipinski_ro5?.hbd_pass],['H-bond acceptors ≤ 10',p.lipinski_ro5?.hba_pass]].map(([x,ok])=><div key={x}><span>{x}</span><b className={ok?'pass':'fail'}>{ok?'Pass':'Review'}</b></div>)}</div><div className="pains"><b>PAINS filter</b><span className={p.pains?.flagged?'fail':'pass'}>{p.pains?.alert}</span></div></div><div className="glass-card"><h2>Property radar</h2><p className="muted">Relative physicochemical profile (0–100 normalised display).</p><div className="radar"><ResponsiveContainer><RadarChart data={radar}><PolarGrid stroke="#454545"/><PolarAngleAxis dataKey="k" tick={{fill:'#aaa',fontSize:10}}/><Radar dataKey="v" stroke="#b9ff62" fill="#b9ff62" fillOpacity={.28}/></RadarChart></ResponsiveContainer></div></div></section></> }

export default function ResearchTools({ page, result, onResult, onNavigate, modelInfo }) {
  const [query, setQuery] = useState(''); const [matches, setMatches] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const [moleculeInput, setMoleculeInput] = useState(''); const [focusResult, setFocusResult] = useState(null); const shown = focusResult || result;
  const [label, Icon] = title[page];
  const search = async () => { if (!query.trim()) return setError('Enter a SMILES string or compound name.'); setLoading(true); setError(''); try { const r = await fetch(`/api/similarity?smiles=${encodeURIComponent(query)}`); const d = await r.json(); if (!r.ok) throw new Error(d.detail); setMatches(d); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const inspect = async () => { if (!moleculeInput.trim()) return setError('Enter a SMILES string or compound name.'); setLoading(true); setError(''); try { const r=await fetch('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({smiles:moleculeInput})}); const d=await r.json(); if(!r.ok) throw new Error(d.detail); setFocusResult(d); onResult(d); } catch(e){setError(e.message)} finally{setLoading(false)} };
  const printReport = () => { if (!result) return; const w = window.open('', '_blank'); w.document.write(`<html><title>OcularTox AI report</title><body style="font:16px Arial;padding:48px;color:#101827"><h1>OcularTox AI — Prediction Report</h1><p><b>Prepared by:</b> Shubhangini</p><hr/><h2>${result.prediction === 'Toxic' ? 'Ocular Toxic' : 'Non-Toxic'} — ${(result.probability_toxic*100).toFixed(1)}% toxicity probability</h2><p><b>Compound Name:</b> ${result.compound_name || 'Unknown'}</p><p><b>Input:</b> ${result.input_smiles}</p><p><b>Canonical SMILES:</b> ${result.canonical_smiles}</p><p><b>Threshold:</b> ${result.threshold_used} &nbsp; <b>Applicability domain:</b> ${result.ad_status}</p><h3>Properties</h3><pre>${JSON.stringify(result.properties, null, 2)}</pre><p>Computational prediction only. Do not use as a substitute for experimental or regulatory assessment.</p></body></html>`); w.document.close(); w.print(); };
  return <div className="research-page"><header className="page-heading"><div className="heading-icon"><Icon size={25}/></div><div><p className="eyebrow">Research module</p><h1>{label}</h1><p>{page === 'similarity' ? 'Compare a query molecule with the local DARTQSAR reference library.' : 'Scientific evidence linked to the latest inference result.'}</p></div></header>
    {['molecule','explain','descriptors'].includes(page) && <div className="inspect-bar"><input className="input-text" value={moleculeInput} onChange={e=>setMoleculeInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&inspect()} placeholder="Enter SMILES or compound name to inspect…"/><button className="btn-primary" onClick={inspect} disabled={loading}>{loading?'Analysing…':'Analyse molecule'}</button></div>}{error && page !== 'similarity' && <p className="error-text">{error}</p>}
    {page === 'about' && <section className="glass-card prose"><h2>Ocular toxicity, made explainable</h2><p>OcularTox AI predicts the likelihood of ocular toxicity directly from chemical structure. It uses a frozen ExtraTrees model with filtered RDKit 2D descriptors, an optimised 0.45 decision threshold, SHAP-based feature explanations, and an applicability-domain signal.</p><div className="metric-row"><div><strong>4,901</strong><span>reference compounds</span></div><div><strong>0.880</strong><span>internal AUC</span></div><div><strong>0.751</strong><span>external AUC</span></div></div><p className="disclaimer">For research and screening support only. Predictions are not clinical, regulatory, or experimental conclusions.</p></section>}
    {page === 'analytics' && <section className="glass-card"><div className="metric-row"><div><strong>80.9%</strong><span>scaffold AUC</span></div><div><strong>75.1%</strong><span>external AUC</span></div><div><strong>0.45</strong><span>toxicity threshold</span></div></div><div className="insight"><AlertTriangle size={20}/><span>Scaffold validation is intentionally stricter than random splitting. Treat predictions for structurally novel molecules with added caution.</span></div></section>}
    {page === 'molecule' && (shown ? <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}><section className="glass-card molecule-stage"><div dangerouslySetInnerHTML={{__html: shown.svg}}/><div><span className="result-kicker">Canonical structure</span><h2>{shown.compound_name}</h2><code style={{ fontSize: '11px', display: 'block', margin: '4px 0 10px', color: '#aaa', wordBreak: 'break-all' }}>{shown.canonical_smiles}</code><p>Input accepted and standardized to its largest molecular fragment. Formula: <b>{shown.properties?.formula}</b></p><span className={`badge ${shown.prediction === 'Toxic' ? 'badge-toxic' : 'badge-safe'}`}>{shown.prediction}</span></div></section><DisclaimerAlert /></div> : <Empty onNavigate={onNavigate}/>) }
    {page === 'descriptors' && (shown ? <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}><DescriptorPanel result={shown}/><DisclaimerAlert /></div> : <Empty onNavigate={onNavigate}/>) }
    {page === 'explain' && (shown ? <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}><section className="glass-card"><h2>Why this prediction? ({shown.compound_name})</h2><p className="muted">The model compares this molecule’s descriptors with its learned training patterns. Red bars pushed risk higher; green bars pushed it lower. Larger bars had more influence.</p><div className="explain-summary"><strong>{shown.prediction}</strong><span>{(shown.probability_toxic*100).toFixed(1)}% toxicity probability · {shown.ad_status}</span></div><div className="chart-wrapper" style={{ background: '#101216', border: '1px solid #20242c', borderRadius: '16px', padding: '20px', marginTop: '20px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}><span style={{ fontSize: '11px', fontFamily: 'var(--mono)', color: '#888', textTransform: 'uppercase' }}>Feature SHAP Contribution (Log-Odds Impact)</span><div style={{ display: 'flex', gap: '12px', fontSize: '10px' }}><span style={{ display: 'flex', alignItems: 'center', gap: '4px', color: '#ff5f78' }}><span style={{ width: '8px', height: '8px', background: '#ff5f78', borderRadius: '2px' }} /> Promotes Toxicity</span><span style={{ display: 'flex', alignItems: 'center', gap: '4px', color: '#b9ff62' }}><span style={{ width: '8px', height: '8px', background: '#b9ff62', borderRadius: '2px' }} /> Promotes Safety</span></div></div><div style={{ height: '320px' }}><ResponsiveContainer width="100%" height="100%"><BarChart data={shown.shap_explanation} layout="vertical" margin={{ top: 5, right: 20, left: 10, bottom: 5 }}><XAxis type="number" stroke="#444" tick={{ fill: '#888', fontSize: 10 }} /><YAxis type="category" dataKey="feature" stroke="#444" tick={{ fill: '#ccc', fontSize: 10, fontFamily: 'var(--mono)' }} width={150} /><Tooltip contentStyle={{ background: '#14161a', border: '1px solid #282d35', borderRadius: '8px', fontSize: '11px' }} itemStyle={{ color: '#fff' }} cursor={{ fill: 'rgba(255,255,255,0.02)' }} /><Bar dataKey="impact" radius={[0, 4, 4, 0]}>{shown.shap_explanation.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.impact > 0 ? '#ff5f78' : '#b9ff62'} />)}</Bar></BarChart></ResponsiveContainer></div></div><div className="descriptor-meaning">{shown.shap_explanation?.map(x=><div key={x.feature}><b>{x.feature}</b><span>{x.impact>0?'Increased the model’s toxicity score':'Reduced the model’s toxicity score'} ({Math.abs(x.impact).toFixed(3)})</span></div>)}</div></section><DisclaimerAlert /></div> : <Empty onNavigate={onNavigate}/>) }
    {page === 'similarity' && <section className="glass-card"><h2>Reference-library comparison</h2><p className="muted">Similarity uses Morgan fingerprints and Tanimoto score. The dataset is read only; it never changes the trained model.</p><div className="tool-input"><input className="input-text" value={query} onChange={e=>setQuery(e.target.value)} placeholder="SMILES or compound name, e.g. aspirin"/><button className="btn-primary" onClick={search} disabled={loading}>{loading ? 'Searching…' : <><Search size={17}/> Find analogues</>}</button></div>{error && <p className="error-text">{error}</p>}{matches && (matches.reference_available ? <div className="similarity-list">{matches.results.map((m,i)=><div key={i}><code>{m.smiles}</code><span>{(m.similarity*100).toFixed(1)}% match</span></div>)}</div> : <div className="insight"><AlertTriangle size={20}/><span>The optional reference spreadsheet is not available. Predictions remain available because the saved model contains all inference parameters.</span></div>)}</section>}
    {page === 'report' && (result ? <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}><section className="glass-card report-card"><FileDown size={36}/><h2>Export prediction report</h2><p>Create a clean, print-ready report for the current prediction. Select “Save as PDF” in the print dialogue.</p><button className="btn-primary" onClick={printReport}>Generate print-ready report</button></section><DisclaimerAlert /></div> : <Empty onNavigate={onNavigate} text="Run a prediction before preparing a report."/>)}
  </div>;
}
