import React, { useState } from 'react';
import { Play, Sparkles, ShieldAlert, CheckCircle2, ListOrdered, X, Copy, AlertTriangle } from 'lucide-react';

export function DisclaimerAlert() {
  return (
    <div className="scientific-disclaimer-card">
      <div className="disclaimer-title">
        <AlertTriangle size={15} style={{ color: 'var(--orange)' }} />
        <span>Scientific Disclaimer</span>
      </div>
      <p className="disclaimer-text">
        Predictions are based on DARTQSAR experimental assay data and reflect laboratory conditions, not everyday exposure levels. Results should be interpreted alongside expert toxicological review.
      </p>
    </div>
  );
}

export default function SinglePredictor({ onResult }) {
  const [input, setInput] = useState(''); const [queue, setQueue] = useState([]); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const entries = (text) => text.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);
  const addQueue = () => { const items = entries(input); if (!items.length) return setError('Enter at least one SMILES string or compound name.'); setQueue(q => [...q, ...items.map(value => ({value, state:'queued'}))]); setInput(''); setError(''); };
  const runQueue = async () => { if (!queue.some(q=>q.state==='queued') || loading) return; setLoading(true); setError(''); let next = queue.findIndex(q=>q.state==='queued'); while (next >= 0) { const item=queue[next]; setQueue(q=>q.map((x,i)=>i===next?{...x,state:'running'}:x)); try { const r=await fetch('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({smiles:item.value})}); const d=await r.json(); if(!r.ok) throw new Error(d.detail); setResult(d); onResult(d); setQueue(q=>q.map((x,i)=>i===next?{...x,state:'done',prediction:d.prediction}:x)); } catch(e) { setQueue(q=>q.map((x,i)=>i===next?{...x,state:'error',error:e.message}:x)); setError(e.message); } next = queue.findIndex((q,i)=>i>next && q.state==='queued'); } setLoading(false); };
  const direct = async () => { const items=entries(input); if (!items.length) return setError('Enter a SMILES string or compound name.'); if (items.length > 1) return setError('For multiple compounds, use “Add to queue”, then run the queue.'); const value = items[0]; setLoading(true); setError(''); try { const r = await fetch('/api/predict', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({smiles:value}) }); const d = await r.json(); if (!r.ok) throw new Error(d.detail); setResult(d); onResult(d); setQueue(q=>[...q,{value,state:'done',prediction:d.prediction}]); setInput(''); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <div className="prediction-lab"><header className="page-heading"><div className="heading-icon"><Sparkles size={25}/></div><div><p className="eyebrow">Inference workspace</p><h1>Single prediction lab</h1><p>Paste one compound or a whole list. Items are processed in a transparent, one-by-one queue.</p></div></header><div className="lab-grid"><section className="glass-card input-card"><div className="section-head"><h2>Compound intake</h2><span>SMILES / name</span></div><textarea className="input-text queue-textarea" value={input} onChange={e=>setInput(e.target.value)} placeholder={'CCO\nAspirin\nCaffeine\n\nSeparate multiple inputs with a new line, comma, or semicolon.'}/><div className="button-row"><button className="btn-secondary" onClick={addQueue}><ListOrdered size={17}/> Add to queue</button><button className="btn-primary" onClick={direct} disabled={loading}><Play size={17}/> Predict input</button></div>{error && <p className="error-text">{error}</p>}<div className="queue-panel"><div><h3>Prediction queue</h3><span>{queue.length} items</span></div>{queue.length===0?<p className="muted">Your queued compounds will appear here.</p>:queue.map((item,i)=><div className={`queue-item ${item.state}`} key={`${item.value}-${i}`}><span>{i+1}</span><code title={item.value}>{item.value}</code><em>{item.prediction || item.error || item.state}</em><button onClick={()=>setQueue(q=>q.filter((_,index)=>index!==i))}><X size={14}/></button></div>)}{queue.some(q=>q.state==='queued')&&<button className="queue-run" onClick={runQueue} disabled={loading}>{loading?'Processing queue…':'Run queued predictions'}</button>}</div></section><section>{result?<Result result={result}/>:<div className="empty-state result-empty"><Sparkles size={34}/><p>Prediction evidence will appear here.</p><small>The model is frozen and is never retrained during use.</small></div>}</section></div></div>;
}
function Result({result}) { const toxic=result.prediction==='Toxic'; return <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}><div className={`result-console ${toxic?'toxic':'safe'}`}><div className="result-top"><div><p className="eyebrow">Latest inference</p><h2>{toxic?'Ocular Toxic':'Non-Toxic'}</h2><div className="result-compound-name" style={{ fontWeight: 700, color: 'var(--lime)', fontSize: '13px', margin: '4px 0 8px' }}>{result.compound_name || 'Unknown Compound'}</div><p style={{ fontFamily: 'var(--mono)', fontSize: '10px', color: '#aaa', wordBreak: 'break-all' }}>{result.canonical_smiles}</p></div><div className="result-symbol">{toxic?<ShieldAlert/>:<CheckCircle2/>}</div></div><div className="probability"><div><span>Toxicity probability</span><strong>{(result.probability_toxic*100).toFixed(1)}%</strong></div><i><b style={{width:`${result.probability_toxic*100}%`}}/></i></div><div className="result-meta"><div><span>Decision threshold</span><strong>{result.threshold_used}</strong></div><div><span>Applicability domain</span><strong>{result.ad_status}</strong></div><div><span>Confidence signal</span><strong>{result.ad_confidence}</strong></div></div><div className="structure-preview" dangerouslySetInnerHTML={{__html:result.svg}}/><button className="copy-smiles" onClick={()=>navigator.clipboard?.writeText(result.canonical_smiles)}><Copy size={14}/> Copy canonical SMILES</button></div><DisclaimerAlert /></div> }
